"""
Clean and enrich the DEX pool hourly and daily time-series.

Inputs:
    data_raw/DEX/pool_hour_data.csv   (produced by reconstruct_pool_timeseries_from_swaps.py;
                                       fallback: fetch_uniswap_pool_timeseries.py)
    data_raw/DEX/pool_day_data.csv

Note: pool_hour_data.csv is generated by reconstruct_pool_timeseries_from_swaps.py, which
stores the sqrtPriceX96-derived ETH price as `token0_price`. This is the accurate on-chain
price (NOT the stale subgraph pool_token0_price). All downstream calculations use this
x96-derived price for DEX-CEX basis and log returns.

Key variables derived:
    eth_usdc_price  - token0_price (x96-derived USDC per WETH; accurate on-chain price)
    eth_usdc_open/high/low/close  - OHLC from x96-derived prices
    fee_rate        - fixed 0.0005 (the 5 bps pool tier)
    fee_apr_ann     - annualized fee APR = (fees_usd / tvl_usd) * 24 * 365.25 (hourly)
                                          (fees_usd / tvl_usd) * 365.25      (daily)
    vol_over_tvl    - volume_usd / tvl_usd  (hourly turnover ratio)
    log_return_1h   - log(close_n / close_{n-1})

Outputs:
    data_processed/DEX/dex_pool_hourly.csv
    data_processed/DEX/dex_pool_daily.csv
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DATA_RAW     = PROJECT_ROOT / "data_raw" / "DEX"
DATA_OUT     = PROJECT_ROOT / "data_processed" / "DEX"

FEE_RATE = 0.0005


def enrich_hourly(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["timestamp_utc"] = pd.to_datetime(df["period_start_unix"], unit="s", utc=True)
    df = df.set_index("timestamp_utc").sort_index()

    df.rename(columns={
        "token0_price": "eth_usdc_price",
        "open":  "eth_usdc_open",
        "high":  "eth_usdc_high",
        "low":   "eth_usdc_low",
        "close": "eth_usdc_close",
    }, inplace=True)

    df["fee_rate"] = FEE_RATE

    tvl = df["tvl_usd"].replace(0, np.nan)
    df["fee_apr_ann"] = (df["fees_usd"] / tvl) * 24 * 365.25
    df["vol_over_tvl"] = df["volume_usd"] / tvl

    df["log_return_1h"] = np.log(df["eth_usdc_close"] / df["eth_usdc_close"].shift(1))

    return df


def enrich_daily(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["date"] = pd.to_datetime(df["date_unix"], unit="s", utc=True).dt.date

    df.rename(columns={
        "token0_price": "eth_usdc_price",
        "open":  "eth_usdc_open",
        "high":  "eth_usdc_high",
        "low":   "eth_usdc_low",
        "close": "eth_usdc_close",
    }, inplace=True)

    df["fee_rate"] = FEE_RATE

    tvl = df["tvl_usd"].replace(0, np.nan)
    df["fee_apr_ann"] = (df["fees_usd"] / tvl) * 365.25
    df["vol_over_tvl"] = df["volume_usd"] / tvl

    return df.sort_values("date_unix").reset_index(drop=True)


def main() -> None:
    DATA_OUT.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("DEX Pool Time-Series Processing")
    print("=" * 60)

    # ── Hourly ───────────────────────────────────────────────────────────────
    hour_path = DATA_RAW / "pool_hour_data.csv"
    if not hour_path.exists():
        print(f"[WARN] {hour_path} missing - run fetch_uniswap_pool_timeseries.py first.")
    else:
        df_hour = pd.read_csv(hour_path)
        df_hour = enrich_hourly(df_hour)
        out_h   = DATA_OUT / "dex_pool_hourly.csv"
        df_hour.to_csv(out_h)
        print(f"Saved {out_h}  ({len(df_hour):,} rows)")
        print(f"  Period: {df_hour.index.min()} -> {df_hour.index.max()}")
        print(f"  fee_apr_ann  mean: {df_hour['fee_apr_ann'].mean():.2%}")
        print(f"  vol_over_tvl mean: {df_hour['vol_over_tvl'].mean():.4f}")

    # ── Daily ────────────────────────────────────────────────────────────────
    day_path = DATA_RAW / "pool_day_data.csv"
    if not day_path.exists():
        print(f"[WARN] {day_path} missing - run fetch_uniswap_pool_timeseries.py first.")
    else:
        df_day = pd.read_csv(day_path)
        df_day = enrich_daily(df_day)
        out_d  = DATA_OUT / "dex_pool_daily.csv"
        df_day.to_csv(out_d, index=False)
        print(f"Saved {out_d}  ({len(df_day):,} rows)")

    print("\nDONE")


if __name__ == "__main__":
    main()
